databases:
  - name: chatapp-db
    plan: free
    databaseName: chatapp
    user: chatapp

services:
  - type: web
    name: chatapp
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: cd web && daphne -b 0.0.0.0 -p $PORT web.asgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: chatapp-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.12.0"
